<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="3" ignored="0" total="9" passed="5" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-08T10:16:51 EET" name="Default Suite" finished-at="2022-12-08T10:16:59 EET" duration-ms="8127">
    <groups>
      <group name="negative">
        <method signature="AuthenticationServiceTest.testInvalidAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" name="testInvalidAuthentication" class="net.absoft.AuthenticationServiceTest"/>
      </group> <!-- negative -->
      <group name="positive">
        <method signature="AuthenticationServiceTest.failingTest()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" name="failingTest" class="net.absoft.AuthenticationServiceTest"/>
        <method signature="AuthenticationServiceTest.testSuccessfulAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" name="testSuccessfulAuthentication" class="net.absoft.AuthenticationServiceTest"/>
      </group> <!-- positive -->
    </groups>
    <test started-at="2022-12-08T10:16:51 EET" name="AuthService" finished-at="2022-12-08T10:16:59 EET" duration-ms="8127">
      <class name="net.absoft.AuthenticationServiceTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:51 EET" name="setUp" finished-at="2022-12-08T10:16:51 EET" duration-ms="16" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="failingTest()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:51 EET" name="failingTest" description="failing test to check retry analyzer" finished-at="2022-12-08T10:16:53 EET" duration-ms="2001" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing test!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing test!
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method retried="true" signature="failingTest()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:53 EET" name="failingTest" description="failing test to check retry analyzer" finished-at="2022-12-08T10:16:55 EET" duration-ms="2000" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing test!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing test!
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:53 EET" name="setUp" finished-at="2022-12-08T10:16:53 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method retried="true" signature="failingTest()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:55 EET" name="failingTest" description="failing test to check retry analyzer" finished-at="2022-12-08T10:16:57 EET" duration-ms="2001" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing test!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing test!
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:55 EET" name="setUp" finished-at="2022-12-08T10:16:55 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="failingTest()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:57 EET" name="failingTest" description="failing test to check retry analyzer" finished-at="2022-12-08T10:16:59 EET" duration-ms="2000" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Failing test!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Failing test!
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failingTest -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:57 EET" name="setUp" finished-at="2022-12-08T10:16:57 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="testInvalidAuthentication" description="Authentication with incorrect credentials" data-provider="invalidLogins" finished-at="2022-12-08T10:16:59 EET" duration-ms="16" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Response{code=400, message='Email should not be empty string'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAuthentication -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="setUp" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="setUp" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="setUp" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="setUp" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="testInvalidAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="testInvalidAuthentication" description="Authentication with incorrect credentials" data-provider="invalidLogins" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[wrong_password1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Response{code=401, message='Invalid email or password'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAuthentication -->
        <test-method signature="testInvalidAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="testInvalidAuthentication" description="Authentication with incorrect credentials" data-provider="invalidLogins" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Response{code=400, message='Password should not be empty string'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAuthentication -->
        <test-method signature="testInvalidAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="testInvalidAuthentication" description="Authentication with incorrect credentials" data-provider="invalidLogins" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Response{code=400, message='Invalid email'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testInvalidAuthentication -->
        <test-method signature="testSuccessfulAuthentication(java.lang.String,java.lang.String,net.absoft.data.Response)[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="testSuccessfulAuthentication" description="Successful authentication" data-provider="validLogin" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[user1@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[password1]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Response{code=200, message='Ok'}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccessfulAuthentication -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:net.absoft.AuthenticationServiceTest@67c27493]" started-at="2022-12-08T10:16:59 EET" name="setUp" finished-at="2022-12-08T10:16:59 EET" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
      </class> <!-- net.absoft.AuthenticationServiceTest -->
    </test> <!-- AuthService -->
  </suite> <!-- Default Suite -->
</testng-results>
