<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-91E2CJV" failures="1" tests="9" name="net.absoft.AuthenticationServiceTest" time="8.034" errors="0" timestamp="2022-12-08T10:16:59 EET" skipped="3">
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.000">
    <failure message="Failing test!" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Failing test!
at org.testng.AssertJUnit.fail(AssertJUnit.java:65)
at net.absoft.AuthenticationServiceTest.failingTest(AuthenticationServiceTest.java:62)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:262)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- failingTest -->
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.016"/>
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.016"/>
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.001">
    <skipped/>
  </testcase> <!-- failingTest -->
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testSuccessfulAuthentication" time="0.000"/>
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.000">
    <skipped/>
  </testcase> <!-- failingTest -->
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.000"/>
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="failingTest" time="2.001">
    <skipped/>
  </testcase> <!-- failingTest -->
  <system-out/>
  <testcase classname="net.absoft.AuthenticationServiceTest" name="testInvalidAuthentication" time="0.000"/>
  <system-out/>
</testsuite> <!-- net.absoft.AuthenticationServiceTest -->
